# Generated by Django 6.0.1 on 2026-01-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Customer ID in Stripe', max_length=255, null=True, unique=True),
        ),
    ]
