# Generated by Django 6.0.1 on 2026-02-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_method',
            field=models.CharField(blank=True, help_text='ID del método de pago por defecto en Stripe', max_length=255, null=True),
        ),
    ]
