# Generated by Django 6.0.1 on 2026-02-14 05:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updated',
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='payment_method',
            field=models.CharField(blank=True, help_text='ID of the default payment method in Stripe.', max_length=255, null=True, verbose_name='default payment method'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: 5522445104', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (e.g., 5522445104).', regex='^\\d{10}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the customer in Stripe.', max_length=255, null=True, unique=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Support Staff'), ('admin', 'Administrator')], default='customer', help_text='Designates whether the user is a regular customer or a wholesaler.', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='User biography or description.', max_length=500, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the email address has been verified.', verbose_name='email verified'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False, help_text='Indicates if the user has opted in to the newsletter.', verbose_name='newsletter subscribed'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the phone number has been verified via SMS.', verbose_name='phone verified'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture.', null=True, upload_to='profile_pictures/%Y/%m/%d/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
