# Generated by Django 6.0.1 on 2026-02-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_updated_customuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('regular_user', 'Regular User'), ('wholesaler', 'Wholesaler')], default='regular_user', help_text='Designates whether the user is a regular customer or a wholesaler.', max_length=20),
        ),
    ]
