# Generated by Django 6.0.1 on 2026-02-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_user_type'),
        ('shop', '0005_product_shop_produc_availab_47d513_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='shop.product', verbose_name='Favorite Products'),
        ),
    ]
