# Generated by Django 6.0.1 on 2026-01-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-valid_to'], 'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
    ]
