# Generated by Django 6.0.1 on 2026-02-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_active_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['active'], name='coupons_cou_active_9d348c_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_to'], name='coupons_cou_valid_f_cf442c_idx'),
        ),
    ]
