# Generated by Django 6.0.1 on 2026-02-13 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0009_alter_orderstatusupdate_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('clarification', 'Solicitar Aclaración'), ('problem', 'Reportar Problema'), ('contact', 'Contactar Soporte'), ('refund', 'Solicitar Reembolso'), ('other', 'Otro')], default='contact', help_text='Tipo de problema', max_length=20)),
                ('subject', models.CharField(help_text='Asunto del ticket', max_length=255)),
                ('message', models.TextField(help_text='Descripción detallada del problema')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En Progreso'), ('waiting_customer', 'Esperando Respuesta'), ('resolved', 'Resuelto'), ('closed', 'Cerrado')], default='open', help_text='Estado del ticket', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', help_text='Prioridad del ticket', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Fecha de resolución', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Pedido relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='orders.order')),
                ('user', models.ForeignKey(help_text='Usuario que creó el ticket', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Contenido del mensaje')),
                ('is_internal', models.BooleanField(default=False, help_text='¿Es una nota interna del equipo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(help_text='Usuario que envió el mensaje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Ticket relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'Mensaje de Ticket',
                'verbose_name_plural': 'Mensajes de Ticket',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', '-created_at'], name='support_sup_user_id_7a4186_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-created_at'], name='support_sup_status_52a4ed_idx'),
        ),
    ]
