# Generated by Django 6.0.1 on 2026-01-30 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(help_text='Stripe ID of the payment method (never disclose to the user)', max_length=255, unique=True)),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], default='visa', help_text='Card type', max_length=20)),
                ('last_four_digits', models.CharField(help_text='Last 4 digits of the card (e.g., 4242)', max_length=4)),
                ('card_holder_name', models.CharField(help_text='Cardholder name', max_length=255)),
                ('exp_month', models.IntegerField(help_text='Expiration month (1-12)')),
                ('exp_year', models.IntegerField(help_text='Expiration year (e.g. 2027)')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default payment method?')),
                ('is_active', models.BooleanField(default=True, help_text='Is the method active? (false if the card has expired or been canceled)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns the payment method', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', '-is_default'], name='payment_pay_user_id_1747ea_idx'), models.Index(fields=['user', '-is_active'], name='payment_pay_user_id_f4fbba_idx')],
            },
        ),
    ]
