# Generated by Django 6.0.1 on 2026-02-14 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_holder_name',
            field=models.CharField(max_length=255, verbose_name='cardholder name'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('diners', 'Diners Club'), ('jcb', 'JCB'), ('other', 'Other')], default='visa', max_length=20, verbose_name='card type'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='exp_month',
            field=models.PositiveSmallIntegerField(verbose_name='expiration month'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='exp_year',
            field=models.PositiveIntegerField(verbose_name='expiration year'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to manually disable this payment method.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='default method'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='last_four_digits',
            field=models.CharField(max_length=4, verbose_name='last 4 digits'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='stripe_payment_method_id',
            field=models.CharField(help_text='Stripe ID for the payment method (pi_... or pm_...).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
