# Generated by Django 6.0.1 on 2026-01-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='aviable',
            new_name='available',
        ),
    ]
