# Generated by Django 5.0.14 on 2026-06-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('source_lang', models.CharField(max_length=5)),
                ('target_lang', models.CharField(max_length=5)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'translation cache',
                'verbose_name_plural': 'translation cache',
                'indexes': [models.Index(fields=['source_hash', 'source_lang', 'target_lang'], name='shop_transl_source__672355_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='translationcache',
            constraint=models.UniqueConstraint(fields=('source_hash', 'source_lang', 'target_lang'), name='unique_translation_entry'),
        ),
    ]
