# Generated by Django 5.0.14 on 2026-08-07 05:06

from django.db import migrations, models


def dedupe_product_slugs(apps, schema_editor):
    """Slug is becoming unique — rename any duplicates before the constraint
    lands so the migration doesn't fail against existing data (e.g. two
    products that happened to slugify to the same value)."""
    Product = apps.get_model("shop", "Product")
    seen = set()
    for product in Product.objects.order_by("id"):
        slug = product.slug
        if slug not in seen:
            seen.add(slug)
            continue
        base, suffix = slug, 2
        while slug in seen:
            slug = f"{base}-{suffix}"
            suffix += 1
        seen.add(slug)
        product.slug = slug
        product.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_sku'),
    ]

    operations = [
        migrations.RunPython(dedupe_product_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
