# Generated by Django 6.0.1 on 2026-01-30 15:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_coupon_order_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, help_text='Discount percentage (0-100) applied at the time of order.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(help_text='Street, number, and apartment', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Additional information (floor, reference, etc.)', max_length=255, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(choices=[('CDMX', 'Ciudad de México'), ('MEX', 'Estado de México'), ('QRO', 'Querétaro')], help_text='State', max_length=50)),
                ('postal_code', models.CharField(help_text='Zip Code', max_length=10)),
                ('country', models.CharField(choices=[('MX', 'México'), ('US', 'Estados Unidos'), ('ES', 'España')], default='MX', help_text='Country', max_length=2)),
                ('phone', models.CharField(help_text='Contact telephone number for shipping', max_length=10)),
                ('recipient_name', models.CharField(help_text='Name of the person receiving the package', max_length=200)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default address?')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], default='home', help_text='Address type', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns the address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', '-is_default'], name='orders_addr_user_id_e66a89_idx'), models.Index(fields=['user', 'created_at'], name='orders_addr_user_id_5d67a7_idx')],
            },
        ),
    ]
