# Generated by Django 6.0.1 on 2026-01-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_discount_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, help_text='Billing address (if different)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordes_billed', to='orders.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='Shipping address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_shipper', to='orders.address'),
        ),
    ]
