# Generated by Django 6.0.1 on 2026-01-30 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_user'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Método de pago utilizado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payment.paymentmethod'),
        ),
    ]
