# Generated by Django 6.0.1 on 2026-01-31 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Customer notes when making the purchase', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, help_text='Estimated delivery date', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes on the order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pedido Pendiente'), ('confirmed', 'Pedido Confirmado'), ('preparing', 'Preparando Pedido'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', help_text='Current order status', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(help_text='Tracking number (e.g., 1Z999AA10123456784)', max_length=255)),
                ('carrier', models.CharField(choices=[('fedex', 'FedEx'), ('ups', 'UPS'), ('dhl', 'DHL'), ('other', 'Otro')], help_text='Parcel delivery company', max_length=20)),
                ('tracking_url', models.URLField(blank=True, help_text='Direct link to tracking (e.g., https://tracking.fedex.com/...)', null=True)),
                ('shipped_at', models.DateTimeField(auto_now_add=True, help_text='Date/time when sent')),
                ('estimated_delivery_date', models.DateField(blank=True, help_text='Estimated delivery date of the carrier', null=True)),
                ('actual_delivery_date', models.DateField(blank=True, help_text='Date when it was actually delivered', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Package weight in kg', max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='Package dimensions (e.g., 30x20x10 cm)', max_length=100, null=True)),
                ('last_location', models.CharField(blank=True, help_text='Last known location of the package', max_length=255, null=True)),
                ('last_status_update', models.DateTimeField(blank=True, help_text='Latest carrier update', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Tracking',
                'verbose_name_plural': 'Order Tracking',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Pedido Pendiente'), ('confirmed', 'Pedido Confirmado'), ('preparing', 'Preparando Pedido'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], help_text='Previous status', max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pedido Pendiente'), ('confirmed', 'Pedido Confirmado'), ('preparing', 'Preparando Pedido'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], help_text='New status', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for change of status', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changed', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order status changed', on_delete=django.db.models.deletion.CASCADE, related_name='status_updated', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Status Change',
                'verbose_name_plural': 'Order Status Changes',
                'indexes': [models.Index(fields=['-order', '-created_at'], name='orders_orde_order_i_9d5f10_idx')],
            },
        ),
    ]
