# Generated by Django 6.0.1 on 2026-02-12 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_customer_notes_order_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusupdate',
            name='order',
            field=models.ForeignKey(help_text='Order status changed', on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='orders.order'),
        ),
    ]
