# Generated by Django 6.0.1 on 2026-02-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_ordertracking_options_ordertracking_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertracking',
            options={'ordering': ['-created'], 'verbose_name': 'Order Tracking', 'verbose_name_plural': 'Order Trackings'},
        ),
    ]
