# Generated by Django 6.0.1 on 2026-02-16 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0004_coupon_coupons_cou_active_9d348c_idx_and_more"),
        ("orders", "0012_alter_ordertracking_options"),
        ("payment", "0002_alter_paymentmethod_card_holder_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["paid"], name="orders_orde_paid_34f5f6_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created"], name="orders_orde_user_id_710475_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status"], name="orders_orde_user_id_02a211_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gte", 0), ("discount__lte", 100)),
                name="order_discount_range",
            ),
        ),
    ]
